// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egvcpzioprxzbbaffdtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndmNwemlvcHJ4emJiYWZmZHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDYwMDcsImV4cCI6MjA2MzkyMjAwN30.ZxObHwgWGQeZiZHliYuafOzOgKZLXRoWq150nTcDKr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);